### ISSUE TITLE
Missed frames on nvidia 390 with ubuntu 16.04

### ISSUE THREAD

**Issue by rmk177** [ChrisDenham/osgopenvrviewer#4]
Good day!
I used your app and found some stuttering in rendering to Vive with GTX 970 and latest SteamVR, OpenVR and OSG from git. hellovr_opengl example works fine without missed frames.
Also I found that at line 715 in hellovr_opengl_main.cpp there is some hack with glFinish();
maybe we need to insert this hack to osgopenvrviewer.

**Comment by ChrisDenham** [comment]
Hi there, thanks for your interest in this project. However, I have no current plans to maintain it as I have moved to Unity for my VR developments.
