### ISSUE TITLE
Integration with osgearth

### ISSUE THREAD

**Issue by jaigsingla** [ChrisDenham/osgopenvrviewer#5]
Hello Chris,

this is an exciting development. 

I am trying to integrate openvrviewer with osgearth viewer ... can you help me in this regard ? 

thanks , 
Jai

**Comment by ChrisDenham** [comment]
Hello Jai,
Thanks for your interest in this project. Sorry, I've not done any work on it for a few years now, as I found my VR and other 3D development so much better and simpler in Unity. So, I have no plans to maintain this project.
Regards.
Chris

**Comment by jaigsingla** [comment]
Hi Chris,

You are right that unity is very easy to use. I am also using unity now a
days. But, your development is very handy if someone wants to work in
native language. So,  request you to guide me in integration with osgearth
viewer.

**Comment by ChrisDenham** [comment]
I can't really guide you, as I know nothing about osgearth. But if it uses the osgviewer class then the example in my sources should get you started with an integration. Feel free to ask any specific questions about it, but I probably won't know the answers.

**Comment by jaigsingla** [comment]
HI Chris,

osgearthviewer also uses osgviewer class. If you can spare sometime to explore this? I have tried to integrate  but  facing unresolved external symbol errors in openvrdevice.obj ..

**Comment by ChrisDenham** [comment]
I'm not sure if I can help, but if you tell me what the unresolved symbols are, I can possibly point you in the right direction.

**Comment by jaigsingla** [comment]
ok. there are 159 unresolved symbols.  errors are like _declspec (dllimport protected )class std::basic_ostream

**Comment by ChrisDenham** [comment]
not sure, sounds like you're just missing the lib for standard library. OSG uses STL, so are you able to build OSG from sources? If you are using Cmake for your project, then it's probably means you are missing a linker setting in your cmake file. sorry i don't have the detail.
